# Pull the base image
FROM mcr.microsoft.com/playwright:v1.48.1-noble

ARG SCOOKIE
ARG CI

ENV CI=$CI
ENV E2E_SHACKLI=$SCOOKIE
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /code/
COPY . /code/

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm test:deps
RUN pnpm build

CMD ["/bin/bash"]
