# Pull the base image
FROM mcr.microsoft.com/playwright:v1.49.0-noble

ARG SCOOKIE
ARG CI

ENV CI=$CI
ENV E2E_SHACKLI=$SCOOKIE
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && \
  pnpm i -g pnpm@latest

COPY package.json pnpm-lock.yaml /code/
WORKDIR /code
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --ignore-scripts --frozen-lockfile

COPY . ./

RUN pnpm postinstall && \
  pnpm test:deps

RUN pnpm build
CMD ["/bin/bash"]
