import {
    arrEmpty,
    arrHas,
    classNames,
    getFileCount,
    getLinkType,
    isFileArr,
    isHTML,
    isIframe,
    isImage,
    isJSON,
    isUrlArr,
    isVideo,
    objContains,
    objContainsProperty,
    objEmpty,
    objHas,
    packValidTypes,
} from "./common";
import type { PostRefs, PreviewReplacements } from "./dom";
import {
    afterElem,
    appendLinksToField,
    convertUrlToLink,
    elementFitsViewport,
    elementIsVisible,
    elemMatches,
    FormDataToJSON,
    generatePreview,
    getCookieValue,
    insertStyle,
    JSONToFormData,
    locatePostRefs,
    matchFileFormat,
    removeChildren,
    safeInnerHTML,
    sanitizeToFragment,
    scrollParentToChild,
    scrollToElement,
    stripHtml,
    superTrim,
} from "./dom";
import type { FetchArgs, ParseType, ShackRSSItem } from "./fetch";
import {
    fetchBackground,
    fetchSafe,
    fetchSafeLegacy,
    parseFetchResponse,
    postBackground,
    safeJSON,
    waitToFetchSafe,
    xhrRequestLegacy,
} from "./fetch";

export {
    stripHtml,
    superTrim,
    insertStyle,
    getCookieValue,
    convertUrlToLink,
    generatePreview,
    scrollToElement,
    scrollParentToChild,
    elementIsVisible,
    elementFitsViewport,
    removeChildren,
    sanitizeToFragment,
    safeInnerHTML,
    FormDataToJSON,
    JSONToFormData,
    appendLinksToField,
    matchFileFormat,
    afterElem,
    elemMatches,
    locatePostRefs,
};
export { PreviewReplacements, PostRefs };
export {
    xhrRequestLegacy,
    fetchSafeLegacy,
    fetchSafe,
    fetchBackground,
    postBackground,
    waitToFetchSafe,
    safeJSON,
    parseFetchResponse,
};
export { ParseType, FetchArgs, ShackRSSItem };
export {
    arrHas,
    arrEmpty,
    objHas,
    objContains,
    objContainsProperty,
    objEmpty,
    isHTML,
    isJSON,
    classNames,
    isVideo,
    isImage,
    isIframe,
    getLinkType,
    isUrlArr,
    isFileArr,
    getFileCount,
    packValidTypes,
};
